'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("USG.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class %SHIT0%
        '''    Shared Function %SHIT1%(ByVal %SHIT2%() As Byte, %SHIT3% As Integer) As Byte()
        '''        Dim %SHIT4%(0 To (%SHIT2%.Length - %SHIT3%) - 1) As Byte
        '''        Return %SHIT4%
        '''    End Function
        '''
        '''    Shared Sub %SHIT5%(ByVal %SHIT6% As String, ByVal %SHIT7% As String)
        '''        Dim %SHIT8% = New anti.IntegrityCheck
        '''        %SHIT8%.AppExePath = %SHIT7%
        '''        %SHIT8%.AppPath = %SHIT6%
        '''        %SHIT8%.RunCheck()
        '''    End Sub
        '''
        '''    Shared Sub %SHIT17%()
        '''        Dim %SHIT9% As String = Applica [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class %SHIT0%
        '''    Shared Function %SHIT1%(ByVal %SHIT2%() As Byte, %SHIT3% As Integer) As Byte()
        '''        Dim %SHIT4%(0 To (%SHIT2%.Length - %SHIT3%) - 1) As Byte
        '''        Return %SHIT4%
        '''    End Function
        '''
        '''    Shared Sub %SHIT5%(ByVal %SHIT6% As String, ByVal %SHIT7% As String)
        '''        Dim %SHIT8% = New anti.IntegrityCheck
        '''        %SHIT8%.AppExePath = %SHIT7%
        '''        %SHIT8%.AppPath = %SHIT6%
        '''        %SHIT8%.RunCheck()
        '''    End Sub
        '''
        '''    Shared Sub %SHIT17%()
        '''        Dim %SHIT9% As String = Applica [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property String2() As String
            Get
                Return ResourceManager.GetString("String2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
